# TravisCI configuration for sitecrafting/greg

language: php
os:
  - linux
dist: bionic

php:
  # TODO PHP 8.0
  - '7.4'

cache:
  directories:
    - '${HOME}/.composer/cache'

# TODO maybe test building docs at some point

addons:
  apt:
    packages:
      - subversion

install:
  - composer install --no-interaction --prefer-dist
  - bin/install-wp-tests.sh

script:
  - vendor/bin/phpunit --group unit
  # TODO integration tests
  - ./vendor/bin/phpcs --standard=./phpcs.xml test lib
  - vendor/bin/phpstan analyse
