# TravisCI configuration for sitecrafting/greg

language: php
os:
  - linux
dist: bionic

addons:
  apt:
    packages:
      - subversion

services:
  - mysql

php:
  - '7.4'
  # TODO
  #- '8.0'

cache:
  directories:
    - '${HOME}/.composer/cache'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - mysql -e 'GRANT ALL PRIVILEGES ON test.* TO test@localhost IDENTIFIED BY "test";'
  - composer self-update --1

install:
  - composer install --no-interaction --prefer-dist
  - DB_HOST=127.0.0.1 DB_NAME=test DB_USER=test DB_PASS=test bin/install-wp-tests.sh

script:
  - composer run-script test
  - composer run-script sniff
  - composer run-script phpstan
  # TODO
  #- composer run-script docs:build
